version: 1.0
playbook:
  name: Cloud Security Monitoring
  description: Automatically monitors and remediates security threats in cloud infrastructure
  steps:
    - name: Fetch Cloud Security Alerts
      action: GET
      url: https://cloudsecurity.example.com/api/alerts
      headers:
        Authorization: Bearer YOUR_API_KEY
      save_as: cloud_alerts
    
    - name: Analyze Alerts
      action: POST
      url: https://soarplatform.example.com/api/alerts/analyze
      headers:
        Authorization: Bearer YOUR_API_KEY
      body:
        alerts: "{{cloud_alerts}}"
      save_as: analysis_results
    
    - name: Remediate Threats
      action: POST
      url: https://cloudsecurity.example.com/api/remediate
      headers:
        Authorization: Bearer YOUR_API_KEY
      body:
        threats: "{{analysis_results.threats}}"
    
    - name: Notify Cloud Security Team
      action: POST
      url: https://hooks.slack.com/services/YOUR/WEBHOOK/URL
      body:
        text: "Cloud security threats detected and remediated. Details: {{analysis_results}}"
