version: 1.0
playbook:
  name: Critical Vulnerability Patch Management
  description: Automatically manages the patching of critical vulnerabilities
  steps:
    - name: Fetch Vulnerability Details
      action: GET
      url: https://soarplatform.example.com/api/vulnerabilities/{{vulnerability_id}}
      headers:
        Authorization: Bearer YOUR_API_KEY
      save_as: vulnerability_details
    
    - name: Schedule Patching
      action: POST
      url: https://soarplatform.example.com/api/patches/schedule
      headers:
        Authorization: Bearer YOUR_API_KEY
      body:
        vulnerability_id: "{{vulnerability_details.id}}"
        systems: "{{vulnerability_details.affected_systems}}"
    
    - name: Notify System Administrators
      action: POST
      url: https://hooks.slack.com/services/YOUR/WEBHOOK/URL
      body:
        text: "Critical vulnerability {{vulnerability_details.id}} detected. Patching scheduled for affected systems. Details: {{vulnerability_details.description}}"
