version: 1.0
playbook:
  name: Malware Detection and Response
  description: Automatically handles malware detection incidents
  steps:
    - name: Fetch Incident Details
      action: GET
      url: https://soarplatform.example.com/api/incidents/{{incident_id}}
      headers:
        Authorization: Bearer YOUR_API_KEY
      save_as: incident_details
    
    - name: Analyze Malware
      action: POST
      url: https://soarplatform.example.com/api/malware/analyze
      headers:
        Authorization: Bearer YOUR_API_KEY
      body:
        incident_id: "{{incident_details.id}}"
      save_as: analysis_results
    
    - name: Isolate Affected Endpoint
      action: POST
      url: https://soarplatform.example.com/api/endpoints/isolate
      headers:
        Authorization: Bearer YOUR_API_KEY
      body:
        endpoint_id: "{{analysis_results.affected_endpoint}}"
    
    - name: Notify Security Team
      action: POST
      url: https://hooks.slack.com/services/YOUR/WEBHOOK/URL
      body:
        text: "Malware detected on endpoint {{analysis_results.affected_endpoint}} and isolation has been performed. Incident ID: {{incident_id}}"
