version: 1.0
playbook:
  name: Security Policy Violation Response
  description: Automatically responds to security policy violations
  steps:
    - name: Detect Policy Violation
      action: GET
      url: https://soarplatform.example.com/api/policy_violations/{{violation_id}}
      headers:
        Authorization: Bearer YOUR_API_KEY
      save_as: violation_details
    
    - name: Enforce Security Policy
      action: POST
      url: https://soarplatform.example.com/api/policies/enforce
      headers:
        Authorization: Bearer YOUR_API_KEY
      body:
        policy_id: "{{violation_details.policy_id}}"
        user_id: "{{violation_details.user_id}}"
    
    - name: Log Policy Violation
      action: POST
      url: https://soarplatform.example.com/api/activity_logs
      headers:
        Authorization: Bearer YOUR_API_KEY
      body:
        violation_id: "{{violation_id}}"
        details: "{{violation_details}}"
    
    - name: Notify Compliance Team
      action: POST
      url: https://hooks.slack.com/services/YOUR/WEBHOOK/URL
      body:
        text: "Security policy violation detected for user {{violation_details.user_id}}. Policy {{violation_details.policy_id}} enforced. Incident ID: {{violation_id}}"
